#-*- coding: utf-8 -*-

{
	"name": "Vit project billplan inherit",
	"version": "1.3", 
	"depends": [
		'vit_project_billplan',
		'sale',
		'report_xlsx',
		'vit_project_rab'
	],
	"author": "cichard.angga51@gmail.com",
	"category": "Utility",
	"website": "My Company",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit project billplan inherited module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"view/project.xml",
		"view/billplan.xml",
		"data/ir_sequence.xml",
		"security/ir.model.access.csv",
		"wizard/billplan.xml",

	],
	"installable": True,
	"auto_install": False,
	"application": True,
}
