#-*- coding: utf-8 -*-

{
	"name": "Vit project billplan",
	"version": "1.0", 
	"depends": [
		'base','project','account','hr'
	],
	"author": "richard.angga51@gmail.com",
	"category": "Utility",
	"website": "My Company",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Vit project billplan module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/bill_plan.xml",
		# "view/project.xml",
		# "view/analytic.xml",
		# "view/department.xml",
		# "view/analytic_tag.xml",
		"report/bill_plan.xml",
		"report/project.xml",
		"report/analytic.xml",
		"report/department.xml",
		"report/analytic_tag.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}